### ISSUE TITLE
IPC: Some more highlighting oddities

### ISSUE THREAD

**Issue by Hendiadyoin1** [kleinesfilmroellchen/serenity-dsl-syntaxhighlight#3]
* [ ] Include style does not follow cpp (# belongs to the include; <> belongs to the file)
* [ ] Empty responses are marked as types
* [ ] The first response parenthesis is marked to belong to the following type

everythis visible below (NotificationServer.ipc)
![grafik](https://user-images.githubusercontent.com/37629766/126537459-9cf72314-71a2-4c55-96a2-c7437fcd0d8b.png)

**Comment by kleinesfilmroellchen** [comment]
# Minor issue with that # should be part of the include but still have its own punctuation formatting that not all themes (like the default ones) apply.
# Empty responses don't seem to cause issues in the image or in my testing.
# Theme artifact, does not show up on themes that format punctuation.

**Comment by Hendiadyoin1** [comment]
OK can confirm,
3 only happens with `Dark+`

**Comment by kleinesfilmroellchen** [comment]
To elaborate on 3: it is probably due to a special formatting for `meta.return-type`. That's nothing I can circumvent, it makes total sense to have the entire return type specification as `meta.return-type`. Also, this key isn't something that themes should usually have formatting for, anyways.
